### ISSUE TITLE
pylint pre-commit? 

### ISSUE THREAD

**Issue by dogfish182** [anancarv/python-artifactory#31]
This project has quite few great features to keep code quality/formatting in order, but it misses basic linting.

I would suggest adding the following 

```
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]

```
to the pre-commit config. 
as this is an easy change but it brings a LOT of linting issues, then I figured I'd offer to implement that as well as fix the issues with the MR. Would this be wanted?
